"""Keyword half of retrieval: the `search_vector` column (tsvector, GIN).

Exact words and phrases: names, section numbers, precise terms. Same table as
the vector half, so filters are literally the same columns and cannot disagree
(ADR-0002).

There is deliberately no write path of its own. `search_vector` is a GENERATED
column - Postgres derives it from `text` on every insert and update - so writing
the row through `indexing.store` maintains the keyword index by construction.
`upsert` here exists so callers can name the half they mean; it is the same
single writer underneath, and it can never fall behind the text it indexes.
"""

from __future__ import annotations

import psycopg

from fylit_rag.indexing.schema import ChunkRecord
from fylit_rag.indexing.search import (
    RESULT_COLUMNS,
    SearchResult,
    build_where,
    table_name,
)
from fylit_rag.indexing.store import UpsertReport, mark_deleted, upsert_chunks


class KeywordIndex:
    """The keyword half. Construct with an open connection."""

    def __init__(self, conn: psycopg.Connection, table: str | None = None):
        self.conn = conn
        self.table = table

    def upsert(self, chunks: list[ChunkRecord]) -> UpsertReport:
        """Write chunk rows; `search_vector` is regenerated by Postgres.

        Calling this and `VectorIndex.upsert` for the same chunks is redundant,
        not harmful - both land on the same row through the same statement.
        """
        return upsert_chunks(self.conn, chunks, table=self.table)

    def search(
        self,
        query: str,
        top_k: int = 20,
        filters: dict | None = None,
    ) -> list[SearchResult]:
        """Chunks matching the query's words, ranked by ts_rank_cd.

        `plainto_tsquery` ANDs the query's terms, which is the right default for
        the keyword half: it is here to nail names, section numbers and exact
        phrases that the vector half blurs. Questions where no chunk contains
        every term simply return nothing, and the vector half carries them.

        `ts_rank_cd` rather than `ts_rank` because it accounts for how close the
        matched terms are to each other - "capital gains tax" appearing as a
        phrase should beat the three words scattered across a long page.
        """
        where, params = build_where(filters)
        table = table_name(self.table)
        columns = ", ".join(f'"{c}"' for c in RESULT_COLUMNS)

        # No table alias, so the shared filter fragment from `build_where` drops
        # in unmodified. plainto_tsquery is written twice rather than aliased in
        # the FROM clause; it is immutable with constant arguments, so Postgres
        # evaluates it once regardless.
        sql = (
            f"SELECT {columns}, "
            f"ts_rank_cd(search_vector, plainto_tsquery('english', %s)) AS rank "
            f"FROM {table} "
            f"WHERE search_vector @@ plainto_tsquery('english', %s) AND {where} "
            f"ORDER BY rank DESC, chunk_id LIMIT %s"
        )
        with self.conn.cursor() as cur:
            cur.execute(sql, [query, query, *params, top_k])
            return [
                SearchResult.from_row(row[:-1], float(row[-1]), rank, "keyword")
                for rank, row in enumerate(cur.fetchall(), start=1)
            ]

    def delete_by_doc(self, doc_id: str) -> int:
        """Mark a document's chunks deleted - see `VectorIndex.delete_by_doc`."""
        return mark_deleted(self.conn, doc_id, table=self.table)
