"""Keyword half of retrieval: the `search_vector` column (tsvector, GIN).

Exact words and phrases: names, section numbers, precise terms. Same table as
the vector half, so filters are literally the same columns and cannot disagree
(ADR-0002).

There is deliberately no write path of its own. `search_vector` is a GENERATED
column - Postgres derives it from `text` on every insert and update - so writing
the row through `indexing.store` maintains the keyword index by construction.
`upsert` here exists so callers can name the half they mean; it is the same
single writer underneath, and it can never fall behind the text it indexes.
"""

from __future__ import annotations

import psycopg

from fylit_rag.indexing.schema import ChunkRecord
from fylit_rag.indexing.store import UpsertReport, mark_deleted, upsert_chunks


class KeywordIndex:
    """The keyword half. Construct with an open connection."""

    def __init__(self, conn: psycopg.Connection, table: str | None = None):
        self.conn = conn
        self.table = table

    def upsert(self, chunks: list[ChunkRecord]) -> UpsertReport:
        """Write chunk rows; `search_vector` is regenerated by Postgres.

        Calling this and `VectorIndex.upsert` for the same chunks is redundant,
        not harmful - both land on the same row through the same statement.
        """
        return upsert_chunks(self.conn, chunks, table=self.table)

    def search(self, query: str, top_k: int = 20, filters: dict | None = None):
        """TODO: ts_rank over search_vector, same filters as the vector half."""
        raise NotImplementedError

    def delete_by_doc(self, doc_id: str) -> int:
        """Mark a document's chunks deleted - see `VectorIndex.delete_by_doc`."""
        return mark_deleted(self.conn, doc_id, table=self.table)
