apiVersion: v1
kind: Service
metadata:
  name: fylit-rag-api
  namespace: fylit-rag
spec:
  selector:
    app: fylit-rag-api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
    - port: 80
      targetPort: 8000
